Use `OwnedFd`/`BorrowedFd` instead of `RawFd`
Smithay/gbm.rs pull request #18
Opened 2022-09-26 20:41 UTC by ids1024

`Device::new_from_fd()` should now be safe since it takes ownership of an `OwnedFd`, but I guess it may be desirable for it to work without ownership of the fd? But then `Device` shouldn't require `T: 'static`.
    
A couple things here would be neater if drm-rs is also updated to use these types.

2022-11-14 18:36 UTC, ids1024 commented
Oh, actually `new_from_fd()` is redundant now since `OwnedFd: AsFd` and `BorrowedFd: AsFd`. I've also dropped the `'static` bound which seems unnecessary.

When https://github.com/Smithay/drm-rs/pull/132, the remaining awkward use of `AsRawFd` can be removed.

2022-12-19 11:34 UTC, Drakulix requested changes
Aside from a small nitpick, this looks good!

2022-12-19 11:34 UTC, Drakulix commented on src/buffer_object.rs
> +        unsafe { BorrowedFd::borrow_raw(ffi::gbm_bo_get_fd(*self.ffi)) }
This implementation is flawed. `gbm_bo_get_fd` returns a new owned file descriptor, that needs to be closed. Casting to a `BorrowedFd` will leak the file descriptor. If we want to drop `AsRawFd`, we need to drop this entirely.

2023-01-03 17:06 UTC, Drakulix approved these changes

2023-01-03 17:07 UTC, merged